package main

func main() {
	//watermelon()
	//domino()
	//wayTooLong()
	//team()
	//nextRound()
	//BitPlus()
	//BeautifulMatrix()
	//PetyaStrings()
	//HelpFulMath()
	//wordCapitalization()
	//BoyOrGirl()
	//StonesOnTheTable()
	//BearAndBigBrother()
	//SoldierAndBananas()
	// Elephant()
	//Word()
	//WrongSubtraction()
	//NearlyLuckNumber()
	//Tram()
	//QueueAtTheSchool()
	//AntonAndDanik()
	//Translation()
	//BeautifulYear()
	//VanyaAndFence()
	//InSearchOfAnEasyProblem()
	//GeorgeAndAccommodation()
	//Presents()
	//Magnets()
	//CalculatingFunction()
	//Drinks()
	//UltraFastMathematician()
	//Hulk()
	//IsYourHorsesShoe()
	//IWannaBeTheGuy()
	//ArrivalOfTheGeneral()
	//InsomniaCure()
	//DivisibilityProblem()
	//Pangram()
	//AntonAndLetters()
	Games()
}
